base: /
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: German
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: German
    hreflang: de-DE
    direction: ltr
    flag: de
    languageId: '0'
rootPageId: 1
routes: {  }
