base: /
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: German
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: ab
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: de
    languageId: '0'
rootPageId: 1
routes: {  }
